### ISSUE TITLE
Error 504 on purl when runing the generate-types command

### ISSUE THREAD

**Issue by COil** [api-platform/schema-generator#104]
[12:09:53] lvernet@lvernet-Z240:~/workspace/$ ./bin/schema generate-types src/ app/config/schema.yml 
PHP Warning:  SimpleXMLElement::__construct(https://purl.org/goodrelations/v1.owl): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
 in /home/lvernet/workspace/vendor/api-platform/schema-generator/src/Command/GenerateTypesCommand.php on line 81

**Comment by dunglas** [comment]
Can you try to update to the last version (it embeds the schemas)

**Comment by COil** [comment]
Hum yes, I was using 1.2. So I'll wait for the other dependency problem to be fixed.

**Comment by COil** [comment]
For me the PHP 7.1 comes from this package, because when I try to install only this component I've got the following error:

    Problem 1
        - api-platform/schema-generator v2.0.1 requires php >=7.1 -> your PHP version (7.0.22) does not satisfy that requirement.

     "require": {
        "php": ">=7.1",

**Comment by COil** [comment]
Hi @dunglas so is the 1.2 version useable?

**Comment by dunglas** [comment]
The version 2 contains a lot of improvements and fixes. You should definitely upgrade.

**Comment by COil** [comment]
The company I work for won't upgrade to PHP 7.1 until the next Debian includes it as the default PHP version. :|
