### ISSUE TITLE
Generate JSON-LD

### ISSUE THREAD

**Issue by dgram** [api-platform/schema-generator#11]
Hi,
I've generated PHP-Models with the php-schema tool.

Now i want to generate JSON-LD code from the given PHP-Models, 
but there is nothing but an note about serializing the data as JSON-LD.
Are there any examples how to serialize/generate the JSON-LD code?
I cant find anything about this in the documentation.

Notice: I does not use symfony, i'm working with zf2.

regards

**Comment by dunglas** [comment]
Hi,

To do that you need a JSON-LD serializer. We provide one as part of the API Platform project but it currently works only with Symfony: https://github.com/dunglas/DunglasApiBundle

Porting it to zf2 should be doable as the code is decoupled but will be a hard task IMO.

**Comment by dgram** [comment]
Hi,

thx for your fast response.
I will try them, when i understood them properly, i have to generate the "Iri" Annotation,
and the DunglasApiBundle specially the parser, and json serializer parse them and serialize them to json-ld?

regards

**Comment by dunglas** [comment]
Exactly. The best way to try it is to install API Platform directly (both PHP Schema and DunglasApiBundle comes preconfigured): https://github.com/dunglas/api-platform

**Comment by dgram** [comment]
thx perfect, i try it
