### ISSUE TITLE
Symfony 4 and wrong path to Entities

### ISSUE THREAD

**Issue by maciekpaprocki** [api-platform/schema-generator#113]
Symfony 4 updates file structure and removes AppBundle folder. 

The easiest solution would be to remove AppBundle from path and change default namespace from AppBundle to App.

**Comment by jlagneau** [comment]
it's not just related to Symfony 4, but 3.4 too AFAIK.

You can change the namespace of your entites like this in your schema.yaml:
```yml
namespace:
    entity: App\Entity

types:
# ...
```
But it'll just create a directory tree `App/Entity`. And if you just remove `App` from the namespace configuration, you'll have to modify every generated entities.

Is there any way to support bundle-less generation or do this require a PR?

**Comment by dunglas** [comment]
Closed by #121
