### ISSUE TITLE
property columnPrefix only allow boolean value

### ISSUE THREAD

**Issue by comxd** [api-platform/schema-generator#118]
...But doctrine allow prefixes like this: `columnPrefix="myprefix_"`

schema.yml:
```
Vehicle:
        properties:
                emissionsCO2: { range: "VehicleEmissionsCO2", embedded: true, columnPrefix: "emissionsCO2_" }
```

Error:
> Invalid type for path "config.types.Vehicle.properties.emissionsCO2.columnPrefix". Expected boolean, but got string.  
  Hint: The property columnPrefix

**Comment by dunglas** [comment]
Closed by #132
