### ISSUE TITLE
Adding custom annotations & @Table annotations 

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/schema-generator#123]
HI there,

I would like to be able to add multi-column uniqueness and custom annotations to fields in my entities for example…

```
@Table(name="video_settings", 
  uniqueConstraints={
    @UniqueConstraint(name="video_unique", 
      columns={"video_dimension", "video_bitrate"}
    )
  }
)
```

… and…

```
/**
 * Some custom comments here
 * 
 * @ApiProperty(iri="http://schema.org/email")
 */
private $property
```

I thought I might be able to do this with a custom annotation generator, however because of the strict configuration, any additional fields are not allowed.

Is there another way to add additional fields to the config without these errors?

I guess it might be possible to add a hook into the existing commands to use a custom Configure class.  Has any work been done on this at all, before I try to find the time to submit a PR?

**Comment by dannylewis-sheffield** [comment]
Hi

The strictness of the configuration is also tripping me up, I would like to see the ability to work with additional custom fields in the config file, bonus points if we could also have ability to extend a default config file.

e.g. schema/person.yaml could contain:

```
defaults: default.yaml
custom: ...

```

defaults.yaml example:
```
author: Bob Down <bob.down@googlemail.com>
header: |
    /*
     * This file is part of the an API package.
     *
     * (c) Bob Down <bob.down@googlemail.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */
annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\SerializerGroupsAnnotationGenerator
    - App\Generator\SchemaAnnotation
```

**Comment by alanpoulain** [comment]
Attributes are now easily customizable, see https://api-platform.com/docs/main/schema-generator/configuration/#adding-a-custom-attribute-or-modifying-a-generated-attribute.
