### ISSUE TITLE
Wrong hard-coded paths for autoload.php

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/schema-generator#129]
Original issue: https://github.com/api-platform/api-platform/issues/684
Author: @danielclariondoor

> Running  "docker-compose exec php vendor/bin/schema" as mentioned in the documentation results in 
> ```
> Warning: require_once(/srv/api/vendor/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /srv/api/vendor/bin/schema on line 15
>
> Fatal error: require_once(): Failed opening required '/srv/api/vendor/bin/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /srv/api/vendor/bin/schema on line 15
> ```

It seems like the `schema` executable doesn't support running from `vendor/bin`. But it'd be better if we could avoid hard-coded paths... (How?)

**Comment by teohhanhui** [comment]
Sorry, I wasn't thinking straight. `vendor/bin` is indeed supported.

**Comment by theofidry** [comment]
@teohhanhui wouldn't it be caused by `vendor` being partially missing?

**Comment by teohhanhui** [comment]
@theofidry I posted comments to that effect, and then deleted them. Haha... Maybe I confuse myself too much.

Now I realize that the path of the `bin/schema` file is always the same relative to the `autoload.php`, regardless of where the `bin-dir` is, as that just creates a symlink.
