### ISSUE TITLE
Parent object properties are also present in their children

### ISSUE THREAD

**Issue by baspeeters** [api-platform/schema-generator#150]
@dunglas  When I define a parent and a child entity (e.g. _Thing_ and its derivative _CreativeWork_) the parent's properties are generated in both classes.

For example, according to schema.org, _CreativeWork_ inherits property `name` from _Thing_. But both classes are generated containing this property, even though class _CreativeWork_ extends _Thing_.

```
types:
  CreativeWork:
    parent: Thing
  Thing:
```

Is this intended behaviour?

Would be happy to write code for adding a flag to disable this in the config as it will allow me to have thinner classes.

**Comment by dunglas** [comment]
Closed by #151
