### ISSUE TITLE
Superseding properties are created as well as those which they supersede

### ISSUE THREAD

**Issue by baspeeters** [api-platform/schema-generator#152]
When using the flag `allProperties`, the properties which supersede other properties are also generated, resulting in the following class with errors regarding duplicate properties:

For example, in [CreativeWork](https://schema.org/CreativeWork), [award](https://schema.org/award) supersedes [awards](https://schema.org/awards).

```
/**
* @var string|null an award won by or for this item
*
* @ORM\Column(type="text", nullable=true)
* @ApiProperty(iri="http://schema.org/award")
*/
private $award;

/**
* @var string|null awards won by or for this item
*
* @ORM\Column(type="text", nullable=true)
*/
protected $award;
```

**Comment by dunglas** [comment]
Closed by #153
