### ISSUE TITLE
[Question] Using normalization_context in ApiPlatformCoreAnnotation

### ISSUE THREAD

**Issue by christiansiewert** [api-platform/schema-generator#155]
Hey,

I wonder if it is possible to use the normalization_context in the @ApiResource annotation. As I see in the docs, you already can use serialization groups for properties but I also need to have normalization_context.

Is that possible?

Best,
Christian

**Comment by alanpoulain** [comment]
You can now easily customize the `ApiResource` attribute, see https://api-platform.com/docs/main/schema-generator/configuration/#adding-a-custom-attribute-or-modifying-a-generated-attribute.
