### ISSUE TITLE
Overwrite twig files

### ISSUE THREAD

**Issue by nickvanderzwet** [api-platform/schema-generator#158]
Is it possible to overwrite the twig template (such as: class.php.twig)?

ApiPlatform uses vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/views/ and there is no (bundle) path configured for the schema-generator.

**Comment by dunglas** [comment]
Not right now, but it could be a nice (and easy to implement) option to add.

**Comment by nickvanderzwet** [comment]
What do you think is a good implementation? The only project-specific configuration file is the schema.yaml

**Comment by dunglas** [comment]
Yes, setting a path containing the templates to use in this file looks good

**Comment by dunglas** [comment]
Closed by #161.
