### ISSUE TITLE
Add support for typed properties

### ISSUE THREAD

**Issue by dunglas** [api-platform/schema-generator#201]
**Description**  
https://www.php.net/manual/en/migration74.new-features.php

**Comment by rand0mdev** [comment]
Hello
Can i help? It's my first OS contribution.

**Comment by azjezz** [comment]
I would like to pick this one up, but I have two questions first:

1. should it be configured ( a new configuration entry ) or just by comparing `PHP_VERSION_ID`?
2. when using typed properties, should all fields now be nullable with `= null;`?

**Comment by alexislefebvre** [comment]
@dunglas is it really an easy pick? :smiley: It could crash an app if the wrong type is put in PHP file.
