### ISSUE TITLE
EasyRdf composer deprecation notice

### ISSUE THREAD

**Issue by divine** [api-platform/schema-generator#207]
**API Platform version(s) affected**: 2.5.7

**Description**  
When running composer update|install there is an error
```
Deprecation Notice: Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class EasyRdf_Serialiser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Serialiser/JsonLd_real.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

**Possible Solution**  

This is related to https://github.com/easyrdf/easyrdf/issues/318 which is fixed in version 1.0, however **schema-generator** didn't have new release since January.

Latest version 2.2.2 has  `"easyrdf/easyrdf": "^0.9"`

Thanks!

**Comment by dunglas** [comment]
Hi, this is handled by https://github.com/api-platform/schema-generator/pull/204

**Comment by ChristopherMatthews** [comment]
I'm running Composer 2.0.4 and still receive the following warnings:

`Class EasyRdf_Serialiser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Serialiser/JsonLd_real.php does not comply with psr-0 autoloading standard. Skipping.`

`Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. Skipping.`

**Comment by dunglas** [comment]
Can you try the linked PR? I hand't the time to finish it until now but it should work (only tests need to be fixed).

**Comment by divine** [comment]
@dunglas 👋 there are a lot of changes in that PR and even if it "works" failing tests doesn't look good.

Maybe bumping **easyrdf/easyrdf** to version 1.0 and releasing new minor release is a better idea until you'll have a time to finish it.

Thanks!

**Comment by divine** [comment]
Oh, I see it now, PR https://github.com/api-platform/schema-generator/pull/196 introduced a breaking changes thus new minor release might be based on https://github.com/api-platform/schema-generator/commit/2938bd2f2dd586f7edafb344f0adca90b100de6b with only bump of **easyrdf/easyrdf** package.

The reason I'm asking for a minor release is basically API-Platform projects that's are based on **=<2.5** versions couldn't be working correctly due to this (breaking changes as well as requiring PHP ^7.4).

I would like to help if you want. 🙂

Thanks!
