### ISSUE TITLE
Add @SerializedName management inside schema.yaml

### ISSUE THREAD

**Issue by kdefives** [api-platform/schema-generator#208]
**Description**  

When we generate classes from yaml, today it is not possible to managed @SerializedName inside the schema.yaml. Consequently, i have to add it manually inside my generated class but it is boring because everytime i regenerate my class using CLI _" vendor/bin/schema generate-types src/ config/schema.yaml "_ , then i have to change my generated class to add @SerializedName again...

**Why do i need to add @SerializedName field inside my generated class?**
Because i need to parse a JSON and for instance, for this type https://schema.org/Product , i receive an array of "image". As it is an array, the schema generator creates variable name "images".
As in my JSON the field is named "image" and not "images", i have to add the " _@SerializedName("image")_ " in order to correctly unserialized my JSON to my class.

Simply, it could be very useful to add the possibility to do that inside schema.yaml : 

```yaml
types:
  # Parent class of Person
  Product:
    properties:
      image: { range: "ImageObject", cardinality: "(0..*)", serializedName: "customNameInsideMyJSON" }

  ImageObject:
    properties:
      identifier: { range: "Text" }
      keywords: ~
```

Then when i execute this : vendor/bin/schema generate-types src/ config/schema.yaml

Automatically my class generated could be (cf. * @SerializedName("image") field inside the "images" attribute declaration):

```php
<?php

declare(strict_types=1);

namespace App\AutoGeneratedModel;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; a haircut; or an episode of a TV show streamed online.
 *
 * @see http://schema.org/Product Documentation on Schema.org
 *
 * @ORM\Entity
 */
class Product
{
/**
     * @var Collection<ImageObject>|null An image of the item. This can be a \[\[URL\]\] or a fully described \[\[ImageObject\]\].
     *
     * @ORM\ManyToMany(targetEntity="App\AutoGeneratedModel\ImageObject")
     * @ORM\JoinTable(name="image", inverseJoinColumns={@ORM\JoinColumn(unique=true)})
     * @SerializedName("customNameInsideMyJSON")
     */
    private $images;

public function addImage(ImageObject $image): void
    {
        $this->images[] = $image;
    }

    public function removeImage(ImageObject $image): void
    {
        $this->images->removeElement($image);
    }

    public function getImages(): Collection
    {
        return $this->images;
    }
}
```

Hope it could help and improve the scheme generator.

Regards

**Comment by alanpoulain** [comment]
You can now add attributes easily, see https://api-platform.com/docs/main/schema-generator/configuration/#adding-a-custom-attribute-or-modifying-a-generated-attribute.
