### ISSUE TITLE
Support namespaces other than schema.org (and fix the Doc)

### ISSUE THREAD

**Issue by DarkGigaByte** [api-platform/schema-generator#22]
Currently the namespace is hardcoded in the TypesGenerator.

(by the way: the "rdfa" configuration key documentation and the name itself is not correct. There is support for many more Parsers in the used Lib EasyRdf than just RDFa. The config key should be renamed at the same moment when other namespaces are supported.)

**Comment by DarkGigaByte** [comment]
IMHO: api-platform would be a lot more powerful with this.

**Comment by dupuchba** [comment]
what other namespaces are you thinking of ?

**Comment by DarkGigaByte** [comment]
No namespace in particular. But here are some examples of Namespaces i would like to use:
- http://purl.org/net/VideoGameOntology
- basically every namespace listed in this awesome Schema Vocab DB http://lov.okfn.org/dataset/lov/vocabs
- custom defined namespaces (e.g. https://api.MyAwesomeExampleDomain.com/)

Most of them are based on schema.org and extend schema.org/Thing

**Comment by dunglas** [comment]
Why not but it will be interesting only if parsers for new vocabularies are added.

**Comment by DarkGigaByte** [comment]
Parser for other Vocab formats are already there. They are in the Lib you are using. ("EasyRdf")
You only have to remove the hardcoded format (and hardcoded schema for other vocabs)

**Comment by dunglas** [comment]
@DarkGigaByte Can you work on a PR on that topic?

**Comment by DarkGigaByte** [comment]
I dont have the time at the moment and i dont know your code _that_ deep ;)
I have just tried a bit to remove the restrictions in the TypesGenerator and then there were other parts of the code that didn't like the new namespaces. I think it would be faster if you have a look at it.

**Comment by dunglas** [comment]
I'll take a look when I'll have some time but it will not be soon as I'm very busy right now.

**Comment by DarkGigaByte** [comment]
Will do the same. ;)

**Comment by DarkGigaByte** [comment]
Please review and test the PR.

**Comment by DarkGigaByte** [comment]
Still a TODO: rename rdfa config option. (it does not have to be an rdfa url anymore) But this would be a breaking change for others.

**Comment by DarkGigaByte** [comment]
...and of course some documentation would be good. ;)

**Comment by dunglas** [comment]
About the rdfa config option, we can deprecate `rdfa` (but keep it for BC) and add a new preferred name.

**Comment by DarkGigaByte** [comment]
Added a test. Don't know how to deprecate a configuration option and provide a replacement and will leave this as todo for you ;)
