### ISSUE TITLE
Publish a generated version to packagist.

### ISSUE THREAD

**Issue by SamMousa** [api-platform/schema-generator#28]
Would it be possible to publish all generated models to packagist?

While the code generator allows me to generate code from schema.org, I cannot code against a common / wellknown interface.

For example https://github.com/php-fig/http-message is a set of interfaces that I can include and code against.

Ideally I'd like to see the same for Schema.org. Since you have built the schema generator I wanted to give you the option first!
If you are not interested I will consider using your generator to generate and publish a repository to packagist!

Cheers

**Comment by dunglas** [comment]
Not sure that it will be useful because the generated code is intended to be edited manually. Maybe exposing interface can be interesting but I think it's the responsibility of the JSON-LD representation (or microdata) to ensure the Schema.org type mapping.

**Comment by dunglas** [comment]
Closing as won't fix.
