### ISSUE TITLE
Support for more recent version of php-cs-fixer

### ISSUE THREAD

**Issue by codedge** [api-platform/schema-generator#330]
Currently this package depends on `php-cs-fixer` `^2.15` which makes is impossible to move to `3.0` of `php-cs-fixer` with the own project.

Would it be possible to either remove the hard dependency or to allow using php cs fixer either `2.x` or `3.x` ?

**Comment by nightio** [comment]
@dunglas any update on it?
I have also tried to upgrade v3.x and I cannot as it's conflict.

Regarding closed PR,
php-cs-fixer is mostly a dev tool and in my opinion, it should not cause conflicts with a top project.

but at the moment both v2.x and v3.x should be supported

**Comment by dunglas** [comment]
Regarding the closed PR, we use PHP CS Fixer as a library in this tool (which is itself a dev tool), not as an external command. To be used as a library, PHP CS Fixer classes must be available downloaded in the vendor directory when Schema Generator is downloaded.

A PR is welcome to add support for the latest version of the tool.

**Comment by nightio** [comment]
@dunglas check it out.
