### ISSUE TITLE
Enabling the possibility to extend FOSUserBundle's BaseUser class 

### ISSUE THREAD

**Issue by restotelry** [api-platform/schema-generator#37]
| Q | A |
| --- | --- |
| Bug fix? | no |
| **New Feature?** | **yes** |
| BC Breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | n/a |
| License | MIT |
| Doc PR |  |

I have a class **Person** and want it to automatically extend the FOSUserbundle's **BaseUser** class each time I'm rung the generator.

``` yaml
# File src/TypesGeneratorConfiguration.php

->prototype('array')
    ->children()
        ->arrayNode('extendsFOSUser')
            ->addDefaultsIfNotSet()
            ->info('Is the class should extend FOSUserBundle?')
            ->children()
                ->scalarNode('namespaceAlias')->defaultNull()->info('The FOSUserBundle namespace alias')->end()
            ->end()
        ->end()
    ...
```

``` php
/** File src/TypesGenerator.php **/

/**
     * @var string
     */
    const FOS_USER_BUNDLE_NAMESPACE = 'FOS\UserBundle\Model\User';
    /**
     * @var string
     */
    const FOS_USER_BUNDLE_NAMESPACE_ALIAS = 'BaseUser';


    /**
     * Generates files.
     */
    public function generate($config)
    {
        $baseClass = [
            ...
            'hasChild' => false,
            'abstract' => false,
            'extendsFOSUser' => false,
        ];
    }

    // Second pass
    foreach ($classes as &$class) {
        ...
        if (isset($config['types'][$class['name']]['extendsFOSUser'])) {
            if (false === $class['parent']) {
                $configFOSNamespaceAlias = $config['types'][$class['name']]['extendsFOSUser']['namespaceAlias'];
                $class['parent'] = null !== $configFOSNamespaceAlias ? $configFOSNamespaceAlias : self::FOS_USER_BUNDLE_NAMESPACE_ALIAS;
                $class['uses'][] = sprintf('%s as %s', self::FOS_USER_BUNDLE_NAMESPACE, $class['parent']);
            } else {
                $this->logger->error(sprintf('[extendsFOSUser] class "%s" already extends class "%s"', $class['name'], $class['parent']));
            }
        }
    }
```

I'd like to check if the FOSUserbundle bundle is:
1/ Installed
2/ Activated

Could someone tell me what's the best practise, please?
Does anyone extend the **Person** class with **FOSUserBundle**? 
How do you manage it, by hand?

Thanks

**Comment by dunglas** [comment]
IMO if we want to support such use cases, it's better to be as generic as possible: you can add an option to the generator to allow to use a custom class (FOSUser or any other class) as `parent`.

But keep in mind that currently, the generator is designed to be run only once (to bootstrap the data model), then fil can be edited.

**Comment by sagikazarmark** [comment]
Not sure if it really makes sense in this particular case.

See some reasoning here:

http://sylius.org/blog/sylius-v0-15-0-with-multiple-channels

**Comment by dunglas** [comment]
Closing as we've deprecated support for FOSUserBundle in API Platform.
