### ISSUE TITLE
Enhancement: Add Unique Constraint Option

### ISSUE THREAD

**Issue by unwarysheep** [api-platform/schema-generator#4]
I think an option should exist to allow a unique constraint on an ORM property, for example:
```
@ORM\Column(type="string", unique=true)
```

I don't yet know the mechanism for implementing this but it would be useful where you want unique entries for some fields in a database (e.g. usernames).

**Comment by dunglas** [comment]
Hi @unwarysheep.

Schema.org doesn't require any field for now. The current typical usage of PHP Schema is:
* pick Schema.org types and property you need
* generate the PHP data model
* edit the generated PHP to match your need (add `unique` constraints, new properties, change cardinalities...)

However, it can be a good idea to have the ability to customize the data model from the config file. IMO the first step is to find a way to let annotations generators exposing their own config. Next, `DoctrineOrmAnnotationGenerator` can parse the config file to look for things like `unique` or `nullable` parameters.

**Comment by unwarysheep** [comment]
Agreed that scheme.org doesn't require the unique property but adding a way for the annotation generators to parse the config would be nice as, for example if you edited the php data model and then regenerated the schema, your edited changes would be lost/overwritten.

**Comment by dunglas** [comment]
@unwarysheep, yes regeneration is tricky and currently become almost impossible when you start editing the generated files. Any help on this (PR, design doc...) is welcome!

**Comment by yelmontaser** [comment]
Done. waiting to merge #27
