### ISSUE TITLE
~ = including all its properties ?

### ISSUE THREAD

**Issue by keyermann** [api-platform/schema-generator#43]
Hi,

In the Api-platform documentation, it is said that `TypeId: ~` = **including all its properties**
```yaml
types: 
  BlogPosting: ~ # A type to generate a PHP entity class from, including all its properties
```
But when I use `bin/schema generate-types src/ app/config/schema.yml`, it generate only the id.
am I doing something wrong ?

Thank you for your assistance ;)

**Comment by dunglas** [comment]
There is probably something wrong, I'll try to take a look asap.

**Comment by TiagoGouvea** [comment]
It keeping happening. It cannot create classes with all schema.org atributes, we need must declare one by one.
