### ISSUE TITLE
Download of schema.org RDFa is unreliable

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/schema-generator#53]
http://schema.org/docs/schema_org_rdfa.html tends to return `Content-Encoding: gzip`

See schemaorg/schemaorg#759

**Comment by danbri** [comment]
We think this is fixed now (https://github.com/schemaorg/schemaorg/issues/759) ... can you confirm?

**Comment by teohhanhui** [comment]
Yes, seems to be fixed. Thank you.
