### ISSUE TITLE
Customize output configuration, retain namespace

### ISSUE THREAD

**Issue by stevenmaguire** [api-platform/schema-generator#6]
Hello, great package. 

I have just begun utilizing this package in one of my projects and have encountered a roadblock. My project utilizes composer and a PSR-4 autoloading namespace to associate all files in `./src` with `Vendor\Package` namespace. 

When configuring the utility I've educated myself on the process of declaring the desired namespace; my current configuration:

``` yml
namespaces:
  entity: "Vendor\Package\Schema"
```

When I execute the following build command:

``` bash
bin/schema generate-types ./src config.yml
```

It creates the directory structure `src > Vendor > Package > Schema`, filled with classes (this does not surprise me; it is what the documentation says), each appropriately namespaced `Vendor\Package\Schema`.

Is there a way to specify the target namespace and a mapping of a base directory to parent namespace such that I can build into my ./src directory and it will create `src > Schema`, filled with my classes, each appropriately namespaced `Vendor\Package\Schema`?

An example from my thoughts might be to include an option in the build command like:

``` bash
bin/schema generate-types ./src config.yml --base-namespace=Vendor\Package
```

Any thoughts?

**Comment by dunglas** [comment]
@stevenmaguire thanks for your feedback.
This is not possible yet but it will be a nice feature to have. It should be a matter of adding a new `namespace > directory` config key.

As a quick fix, you can still use the refactoring feature of PHPStorm or your preferred IDE to move generated classes.
