### ISSUE TITLE
Choose a different entity name

### ISSUE THREAD

**Issue by JDruery** [api-platform/schema-generator#61]
Is it possible to choose a different Entity name than the id from schema.org? For example, if I want to use the Organization type I would list Organization under types in the yaml file. Then the Entity would be called Organization and placed in Organization.php. What if I want to use the Organization type but call the Entity something else (Team, Club, Group, or whatever)? I may have missed this in the documentation, but it looks to me like the only way to do this is to manually refactor the output files in my IDE.

**Comment by JDruery** [comment]
Looked through the source and answered my own question. I'll describe here because it hasn't made it into the docs yet. In the 1.1 version, simply name it whatever you want, then add a "guessFrom" hint to the type, like so:
type:
  Group:
    guessFrom: Organization
    properties:
      name: ~
      ...

**Comment by dunglas** [comment]
Thanks good sharing @JDruery. Can you open a doc PR?

**Comment by JDruery** [comment]
There you go... not sure if I used the correct terminology, feel free to correct as needed. I also added the extra options for cardinality (many to one)

**Comment by dunglas** [comment]
@JDruery can you give me the link to the PR/commit?

**Comment by JDruery** [comment]
Sorry, I didn't realize that I hadn't actually created the PR. Should be there now: https://github.com/api-platform/doc/pull/76
