### ISSUE TITLE
Replace Twig by Nette PHP generator

### ISSUE THREAD

**Issue by dunglas** [api-platform/schema-generator#67]
https://github.com/nette/php-generator

**Comment by teohhanhui** [comment]
Why not https://github.com/nikic/PHP-Parser?

https://github.com/nikic/PHP-Parser/blob/master/doc/4_Code_generation.markdown

**Comment by dunglas** [comment]
I wasn't aware of this feature. Why not!

**Comment by dunglas** [comment]
After a second though, Twig is good enough for or use case.
