### ISSUE TITLE
Adding 2.0 branch for php-cs-fixer 

### ISSUE THREAD

**Issue by acrozes** [api-platform/schema-generator#70]
Why not update composer.json for php-cs-fixer version like:

> "friendsofphp/php-cs-fixer": "^1.12 || ^2.0"

**Comment by dunglas** [comment]
I'm 👍, a PR is welcome (but as we use the fixer API, it probably requires some modifications in the code too).

**Comment by helmuthva** [comment]
Any progress on this?

As https://github.com/janephp/openapi requires ^2.0 of php-cs-fixer there seems to be no chance currently to use both.

**Comment by dunglas** [comment]
You can use the PHAR version of the Schema Generator to avoid dependency problems.

**Comment by helmuthva** [comment]
@dunglas: isn't api-platform/schema-generator a dependency of api platform (which we use?) or am i missing something?

**Comment by dunglas** [comment]
It is but it's just a dev dependency to generate files, in the meantime you can remove it from dev dependencies and use the PHAR.

**Comment by theofidry** [comment]
@helmuthva you have two solutions:

- Use a PHAR with a tool like https://packagist.org/packages/tm/tooly-composer-script to still keep track of it in your project
- Use a tool like https://github.com/bamarni/composer-bin-plugin

I tend to prefer the later as easier to use but both works pretty well

**Comment by dunglas** [comment]
3. open a PR to upgrade the dependency :)
