### ISSUE TITLE
[enhancement] turn enums into embeddables

### ISSUE THREAD

**Issue by Evertt** [api-platform/schema-generator#74]
You can do this by requiring the enum package in the composer.json of this project and then extending it so you can make this:

```php
namespace ApiPlatform\SchemaGenerator;

use Doctrine\ORM\Mapping as ORM;
use MyCLabs\Enum\Enum as OriginalEnum;

/** @ORM\Embeddable */
class Enum extends OriginalEnum
{
    /** @ORM\Column */
    protected $value;
}
```

And of course then making every generated enum extend this enum class.

## edit:

yes I guess this should probably be a part of doctrine itself instead of this schema-generator. But I'm afraid that it would never be implemented in doctrine, so that's why I'm asking here.

**Comment by theofidry** [comment]
As much as I would like to see enums, I'm still not happy with the current user-land implementations. So I would be against introducing a dependency for something like. That said the rest of the team may have a different opinion regarding this.
