### ISSUE TITLE
Upgrade to Twig 2.0?

### ISSUE THREAD

**Issue by backbone87** [api-platform/schema-generator#78]
This package prevents using twig 2.0

Is it basically compatible and just needs an update to the composer.json? if so, it would be nice, if "^1.0 || ^2.0" can be used as the version contraint

```
api-platform/schema-generator  v1.2.0  requires  twig/twig (^1.0)
symfony/symfony                v3.3.2  requires  twig/twig (~1.34|~2.4)
```

**Comment by teohhanhui** [comment]
Already fixed in #69
