### ISSUE TITLE
Documentation link is broken on GitHub

### ISSUE THREAD

**Issue by gunthercox** [api-platform/schema-generator#79]
Currently the link to the documentation is broken (a page with a "Not Found" message is returned when after clicking on it.

![image](https://user-images.githubusercontent.com/2030578/27656797-5cf31b8c-5c18-11e7-81b4-98eb504c1772.png)

A screenshot of the 404 page.

![image](https://user-images.githubusercontent.com/2030578/27656826-7c51fe08-5c18-11e7-9b88-a20ac71cb538.png)

I believe the link is suppose to be https://api-platform.com/docs/schema-generator/

**Comment by dunglas** [comment]
Thanks for the report! Fixed.
